import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import styles from '../styles/Home.module.css'
import Images from '../components/Images'
import Pages from '../components/Pages'
const Home: NextPage = () => {
  const [data, setData] = React.useState({});
  const [currentPage, setCurrentPage] = React.useState(1);
  const [postsPerPage, setPostsPerPage] = React.useState(12);
  const [totalPages, setTotalPages] = React.useState(12);
  
  React.useEffect(() => {
    fetch('https://api.artic.edu/api/v1/artworks')
    .then((respostaServer) => {
      return respostaServer.json();
    })
    .then((respostaConvertida) => {
      console.log("resposta: ", respostaConvertida)
      setData(respostaConvertida.data);
      setTotalPages(respostaConvertida.pagination.total_pages);
      setCurrentPage(respostaConvertida.pagination.current_page);
      setPostsPerPage(respostaConvertida.pagination.limit);
    })
  }, []);

    // Pagination
    const previousClickHandler = () => {
      setCurrentPage(currentPage - 1);
    };
    const nextClickHandler = () => {
      setCurrentPage(currentPage + 1);
    };
    const pageChangeHandler = (page: number) => {
      setCurrentPage(page);
    };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Images src='https://s1.static.brasilescola.uol.com.br/be/conteudo/images/as-montanhas-diferenciam-se-pela-altitude-mais-elevada-em-relacao-as-outras-formas-relevo-5926cccf2e122.jpg' wdt={200} hgt={100}/>
      
        <Pages 
        currentPage={currentPage} 
        onPreviousClick={previousClickHandler} />
      </main>
    </div>
  )
}

export default Home
