import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

import styles from '../styles/Home.module.css'
import List from '../components/List'

import _ from 'lodash'
import { Container } from 'react-bootstrap'
const Home: NextPage = () => {
  const [data, setData] = React.useState<any[]>([]);
  const [currentPage, setCurrentPage] = React.useState(1);
  const [postsPerPage, setPostsPerPage] = React.useState(12);
  const [totalPages, setTotalPages] = React.useState(12);
  
  

  React.useEffect(() => {
    fetch('https://api.artic.edu/api/v1/artworks?page=4&limit=100')
    .then((respostaServer) => {
      return respostaServer.json();
    })
    .then((respostaConvertida) => {
      setData(respostaConvertida.data);
      setTotalPages(respostaConvertida.pagination.total_pages);
      setCurrentPage(respostaConvertida.pagination.current_page);
      setPostsPerPage(respostaConvertida.pagination.limit);
    })
  }, []);
  
    // Pagination
    const previousClickHandler = () => {
      setCurrentPage(currentPage - 1);
    };
    const nextClickHandler = () => {
      setCurrentPage(currentPage + 1);
    };
    const pageChangeHandler = (page: number) => {
      setCurrentPage(page);
    };
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <List data={data} perPage={postsPerPage} />
      </main>
    </Container>
  )
}

export default Home
